# Generated by Django 3.2 on 2021-05-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complete_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='complete_photos')),
                ('user_id', models.IntegerField()),
                ('number_of_humans', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='raw_photos',
        ),
    ]
