# Generated by Django 3.2 on 2021-05-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210527_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete_photos',
            name='photo',
            field=models.ImageField(upload_to='media/complete_photos'),
        ),
    ]
