# Generated by Django 3.2 on 2021-05-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_complete_photos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete_photos',
            name='photo',
            field=models.ImageField(upload_to='complete_photos/'),
        ),
    ]
